export const translations = {
  tr: {
    "tümü": "Tümü",
    gayrimenkul: "Gayrimenkul",
    aydınlatma: "Aydınlatma",
    kurumsal: "Kurumsal",
    "elektrik & elektronik": "Elektrik & Elektronik",
    yazılım: "Yazılım",
    otomasyon: "Otomasyon",
    "bilişim & güvenlik": "Bilişim & Güvenlik",
    "savunma sanayi": "Savunma Sanayi",
    otomotiv: "Otomotiv",
    denizcilik: "Denizcilik",
    "e-ticaret": "E-Ticaret",
    "inşaat & mimarlık": "İnşaat & Mimarlık",
    "hukuk & danışmanlık": "Hukuk & Danışmanlık",
    ürün: "Ürün",
    "plastik & kimya": "plastik & kimya",
    gıda: "Gıda",
    eğitim: "Eğitim",
    sağlık: "Sağlık",
    "Tamamlandı": "Tamamlandı",
    "Devam ediyor": "Devam ediyor",
  },

  en: {
    "tümü": "All",
    gayrimenkul: "Real Estate",
    aydınlatma: "Lighting",
    kurumsal: "Corporate",
    "elektrik & elektronik": "Electrical & Electronics",
    yazılım: "Software",
    otomasyon: "Automation",
    "bilişim & güvenlik": "IT & Security",
    "savunma sanayi": "Defense Industry",
    otomotiv: "Automotive",
    denizcilik: "Maritime",
    "e-ticaret": "E-Commerce",
    "inşaat & mimarlık": "Construction & Architecture",
    "hukuk & danışmanlık": "Law & Consultancy",
    ürün: "Product",
    "plastik & kimya": "Plastics & Chemicals",
    gıda: "Food",
    eğitim: "Education",
    sağlık: "Health",
    "Tamamlandı": "Completed",
    "Devam ediyor": "On-going",
  },
};
